version: '2'
services:
    educationmanagement-app:
        image: educationmanagement
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://educationmanagement-postgresql:5432/EducationManagement
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    educationmanagement-postgresql:
        extends:
            file: postgresql.yml
            service: educationmanagement-postgresql
